############
#
# Copyright (c) 2024 Maxim Yudayev and KU Leuven eMedia Lab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# Created 2024-2025 for the KU Leuven AidWear, AidFOG, and RevalExo projects
# by Maxim Yudayev [https://yudayev.com].
#
# ############

project       : "template"
trial_type    : "test" # recommend "test" for testing and "real" data
subject_id    : 0 # UID of the subject
trial_id      : 0 # UID of the trial
duration_s    : null

print_status  : True
print_debug   : True


host_ip : "192.168.0.100"
remote_publisher_ips: # IPs of Brokers to listen to for data on some of desired topics
  - "192.168.0.103"
  - "192.168.0.104"

is_remote_kill: False
remote_kill_ip: "192.168.0.100" # IP of Broker that delegates the primary kill signal (i.e CLI or GUI)

remote_subscriber_ips: []


logging_spec:
  stream_period_s     : 1
  
  stream_hdf5         : True
  stream_csv          : False
  stream_video        : True
  stream_audio        : False

  dump_csv            : False
  dump_hdf5           : False
  dump_video          : False
  dump_audio          : False

  video_codec         : 'h264_qsv'
  video_codec_num_cpu : 1
  video_pix_format    : 'nv12'

  audio_format        : "wav" # currently only supports WAV


producer_specs:
  # Stream from the Awinda body tracking and Manus gloves.
  - class: "AwindaStreamer"
    device_mapping:
      pelvis          : "00B4D3E4"
      upper_leg_right : "00B4D3D7"
      lower_leg_right : "00B4D3E2"
      foot_right      : "00B4D3DD"
      upper_leg_left  : "00B4D3E7"
      lower_leg_left  : "00B4D3D4"
      foot_left       : "00B4D3D8"
    num_joints        : 7
    sampling_rate_hz  : 100
    radio_channel     : 15
  
  # Stream from the DOTs lower limb tracking.
  - class: "DotsStreamer"
    device_mapping: 
      knee_right      : "40195BFC800B01F2"
      foot_right      : "40195BFC800B003B"
      pelvis          : "40195BFD80C20052"
      knee_left       : "40195BFC800B017A"
      foot_left       : "40195BFD80C200D1"
    master_device     : "pelvis" # wireless dot relaying messages, must match a key in the `device_mapping`
    num_joints        : 5
    sampling_rate_hz  : 60 # [1, 4, 10, 12, 15, 20, 30, 60]
    is_get_orientation: False
    is_sync_devices   : True
  
  # Stream from the Pupil Labs eye tracker, including gaze and video data.
  - class: "EyeStreamer"
    pupil_capture_ip        : "localhost"
    pupil_capture_port      : "50020"
    video_image_format      : "bgr"
    gaze_estimate_stale_s   : 0.2
    is_binocular            : True # uses both eyes for gaze data and for video
    is_stream_video_world   : True
    is_stream_video_eye     : False
    is_stream_fixation      : False
    is_stream_blinks        : False
    shape_video_world:
      - 720
      - 1280
      - 3
    shape_video_eye0:
      - 192
      - 192
      - 3
    shape_video_eye1:
      - 192
      - 192
      - 3
    fps_video_world       : 30.0
    fps_video_eye0        : 120.0
    fps_video_eye1        : 120.0
  
  # Stream from one or more cameras.
  - class: "CameraStreamer"
    camera_mapping: # map camera names (usable as device names in the HDF5 file) to capture device indexes
      basler_north : "40478064"
      basler_east  : "40549960"
      basler_south : "40549975"
      basler_west  : "40549976"
    fps: 30
    resolution:
      - 1440
      - 2560
    camera_config_filepath: "resources/AidFOG/pylon_30fps_2K_40478064.pfs"

  # Moticon insole pressure.
  - class: "InsoleStreamer"
    sampling_rate_hz: 100

  # CyberLeg self-selected task activity.
  - class: "CyberlegStreamer"

  # Moxy blood oxygenation.
  - class: "MoxyStreamer"
    devices:
      - "8523"
      - "8524"
      - "8525"
    sampling_rate_hz: 0.5
  
  # TMSi SAGA device.
  - class: "TmsiStreamer"
    sampling_rate_hz: 20
  
  # Vicon capture system.
  - class': "ViconStreamer"
    device_mapping:
      gluteus_medius_left         : "1" # left upper glute
      rectus_femoris_left         : "2" # left quad
      semitendius_left            : "3" # left hamstring
      medial_gastrocnemius_left   : "4" # left inner calf
      gluteus_medius_right        : "5" # right upper glute
      rectus_femoris_right        : "6" # right quad
      semitendius_right           : "7" # right hamstring
      medial_gastrocnemius_right  : "8" # right inner calf
    sampling_rate_hz: 2000
    vicon_ip: "192.168.0.104"
  
  # Dummy producer.
  - class': "DummyStreamer"
    sampling_rate_hz: 1

consumer_specs: # DataVisualizer and DataLogger are mutually exclusive, select only one.
  - class: "DataVisualizer"
    stream_specs: 
      - class: "ExperimentControlStreamer"
        activities: # Cybathlon activities that you want to label
          - "Balance beam"
          - "Stairs"
          - "Step over"
          - "Slopes"
          - "Bench and table"
          - "Wobbly steps"
          - "High step"
          - "Ladder"
          - "Cross country"
          - "Hurdles"

      - class: "AwindaStreamer"
        device_mapping:
          pelvis          : "00B4D3E4"
          upper_leg_right : "00B4D3D7"
          lower_leg_right : "00B4D3E2"
          foot_right      : "00B4D3DD"
          upper_leg_left  : "00B4D3E7"
          lower_leg_left  : "00B4D3D4"
          foot_left       : "00B4D3D8"
        num_joints        : 7
        sampling_rate_hz  : 100
        radio_channel     : 15
      
      - class: "DotsStreamer"
        device_mapping: 
          knee_right      : "40195BFC800B01F2"
          foot_right      : "40195BFC800B003B"
          pelvis          : "40195BFD80C20052"
          knee_left       : "40195BFC800B017A"
          foot_left       : "40195BFD80C200D1"
        master_device     : "pelvis" # wireless dot relaying messages, must match a key in the `device_mapping`
        num_joints        : 5
        sampling_rate_hz  : 60
        is_get_orientation: False
        is_sync_devices   : True
      
      - class: "EyeStreamer"
        pupil_capture_ip        : "localhost"
        pupil_capture_port      : "50020"
        video_image_format      : "bgr"
        gaze_estimate_stale_s   : 0.2
        is_binocular            : True # uses both eyes for gaze data and for video
        is_stream_video_world   : True
        is_stream_video_eye     : False
        is_stream_fixation      : False
        is_stream_blinks        : False
        shape_video_world: 
          - 720
          - 1280
          - 3
        shape_video_eye0: 
          - 192
          - 192
          - 3
        shape_video_eye1: 
          - 192
          - 192
          - 3
        fps_video_world       : 30.0
        fps_video_eye0        : 120.0
        fps_video_eye1        : 120.0
      
      - class: "CameraStreamer"
        camera_mapping: # map camera names (usable as device names in the HDF5 file) to capture device indexes
          basler_north : "40478064"
          basler_east  : "40549960"
          basler_south : "40549975"
          basler_west  : "40549976"
        fps: 30
        resolution:
          - 1440
          - 2560
        camera_config_filepath: "resources/AidFOG/pylon_30fps_2K_40478064.pfs"
      
      - class: "InsoleStreamer"
        sampling_rate_hz: 100

      - class: "CyberlegStreamer"
      
      - class: "MoxyStreamer"
        devices:
          - "8523"
          - "8524"
          - "8525"
        sampling_rate_hz: 0.5
      
      - class: "TmsiStreamer"
        sampling_rate_hz: 20
      
      - class': "ViconStreamer"
        device_mapping:
          gluteus_medius_left         : "1" # left upper glute
          rectus_femoris_left         : "2" # left quad
          semitendius_left            : "3" # left hamstring
          medial_gastrocnemius_left   : "4" # left inner calf
          gluteus_medius_right        : "5" # right upper glute
          rectus_femoris_right        : "6" # right quad
          semitendius_right           : "7" # right hamstring
          medial_gastrocnemius_right  : "8" # right inner calf
        sampling_rate_hz: 2000
        vicon_ip: "192.168.0.104"
      
      - class': "DummyStreamer"
        sampling_rate_hz: 1
    
    logging_spec:
      stream_period_s     : 1
  
      stream_hdf5         : True
      stream_csv          : False
      stream_video        : True
      stream_audio        : False

      dump_csv            : False
      dump_hdf5           : False
      dump_video          : False
      dump_audio          : False

      video_codec         : 'h264_qsv'
      video_codec_num_cpu : 1
      video_pix_format    : 'nv12'

      audio_format        : "wav" # currently only supports WAV

  # - class: "DataVisualizer"

  # - class: "DummyConsumer"


pipeline_specs: []
