############
#
# Copyright (c) 2024 Maxim Yudayev and KU Leuven eMedia Lab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# Created 2024-2025 for the KU Leuven AidWear, AidFOG, and RevalExo projects
# by Maxim Yudayev [https://yudayev.com].
#
# ############

project       : "AidWear"
trial_type    : "test" # recommend "test" for testing and "real" data
subject_id    : 0 # UID of the subject
trial_id      : 0 # UID of the trial
duration_s    : null

print_status  : True
print_debug   : True


host_ip : "192.168.69.103"
is_master_broker: False
remote_publisher_ips: []
remote_subscriber_ips: 
  - "192.168.69.100"

is_remote_kill: True
remote_kill_ip: "192.168.69.100" # IP of Broker that delegates the primary kill signal (i.e CLI or GUI)
is_master_broker: False


logging_spec:
  stream_period_s     : 10
  
  stream_hdf5         : True
  stream_csv          : False
  stream_video        : True
  stream_audio        : False

  dump_csv            : False
  dump_hdf5           : False
  dump_video          : False
  dump_audio          : False

  video_codec             : 'h264_qsv'
  video_codec_num_cpu     : 1
  video_codec_pix_format  : 'nv12'

  audio_format        : "wav" # currently only supports WAV


producer_specs:
  # Stream from the DOTs lower limb tracking.
  - class: "DotsStreamer"
    device_mapping: 
      knee_right      : "40195BFC800B01F2"
      foot_right      : "40195BFC800B003B"
      pelvis          : "40195BFD80C20052"
      knee_left       : "40195BFC800B017A"
      foot_left       : "40195BFD80C200D1"
    master_device     : "pelvis" # wireless dot relaying messages, must match a key in the `device_mapping`
    num_joints        : 5
    sampling_rate_hz  : 60
    is_get_orientation: False
    is_sync_devices   : True
  
  # Stream from the Pupil Labs eye tracker, including gaze and video data.
  - class: "EyeStreamer"
    pupil_capture_ip        : "localhost"
    pupil_capture_port      : "50020"
    video_image_format      : "bgr"
    gaze_estimate_stale_s   : 0.2
    is_binocular            : True # uses both eyes for gaze data and for video
    is_stream_video_world   : True
    is_stream_video_eye     : False
    is_stream_fixation      : False
    is_stream_blinks        : False
    shape_video_world: 
      - 720
      - 1280
      - 3
    shape_video_eye0: 
      - 192
      - 192
      - 3
    shape_video_eye1: 
      - 192
      - 192
      - 3
    fps_video_world       : 30.0
    fps_video_eye0        : 120.0
    fps_video_eye1        : 120.0

  # Moticon insole pressure.
  - class: "InsoleStreamer"
    sampling_rate_hz: 100


consumer_specs: []


pipeline_specs: []
