project       : "RevalExo"
trial_type    : "test" # recommend "test" for testing and "real" data
subject_id    : 0 # UID of the subject
trial_id      : 0 # UID of the trial
duration_s    : null

host_ip       : "10.244.21.115"
remote_publisher_ips: []
remote_subscriber_ips: []
is_expose_to_remote_sub : False
is_remote_kill : False

print_status  : True
print_debug   : True

logging_spec:
  stream_period_s     : 1
  
  stream_hdf5         : True
  stream_csv          : False
  stream_video        : True
  stream_audio        : False

  dump_csv            : False
  dump_hdf5           : False
  dump_video          : False
  dump_audio          : False

  video_codec         : 'h264_nvenc'
  video_codec_num_cpu : 1
  video_pix_format    : 'nv12'

  audio_format        : "wav" # currently only supports WAV


producer_specs:
  # Vicon capture system.
  - class: "CameraStreamer"
    camera_mapping: # map camera names (usable as device names in the HDF5 file) to capture device indexes
      basler_north : "40478064"
      basler_east  : "40549960"
      basler_south : "40549975"
      basler_west  : "40549976"
    fps: 30
    resolution:
      - 1440
      - 2560
    camera_config_filepath: "resources/AidFOG/pylon_30fps_2K.pfs"
   

consumer_specs: []


pipeline_specs: []
